### ISSUE TITLE
Extending User model

### ISSUE THREAD

**Issue by vladblindu** [mishbahr/django-users2#16]
I'm new to django so please be gentle.
I tried to understand how can I extend the user model. I couldn't find any references in the docs.
It's says: "support for multiple user types (using the awesome django-model-utils)",
but I couldn't find any reference of how it can be done.

**Comment by mishbahr** [comment]
Hey @vladblindu 
Sorry for the lack of documentations. I'll update this comment with an example, as soon as I can.

Thanks
- Mishbah

**Comment by vladblindu** [comment]
Thanks a lot.

**Comment by mishbahr** [comment]
Update — something like this should work.

    # accounts/models.py

        from django.db import models

        from users.models import User 


        class LinkedInUser(User):
            linkedin_id = models.CharField(max_length=30, unique=True)
         
            class Meta:
                verbose_name = _('LinkedIn User')


    # accounts/forms.py

        from users.forms import UserCreationForm


        class LinkedInUserCreationForm(UserCreationForm):
            linkedin_id = forms.CharField(label=_('LinkedIn Id'), max_length=30, required=True,
                                          help_text=_('Required. 30 characters or fewer.'))
         
            class Meta:
                model = LinkedInUser
         

    # accounts/admin.py

        from django.contrib import admin
        from django.contrib.auth.admin import UserAdmin
        from django.utils.translation import ugettext_lazy as _
         
        from .forms import LinkedInUserCreationForm
        from .models import LinkedInUser

         
        class LinkedInUserAdmin(UserAdmin):
            form = LinkedInUserCreationForm
            list_display = ('username', 'email', 'linkedin_id',)
            add_fieldsets = (
                (None, {
                    'classes': ('wide',),
                    'fields': ('username', 'linkedin_id', 'password1', 'password2')}
                ),
            )
            fieldsets = (
                (None, {'fields': ('username', 'password')}),
                (_('Personal info'), {'fields': ('linkedin_id', 'first_name', 'last_name', 'email')}),
                (_('Permissions'), {'fields': ('is_active', 'is_staff', 'is_superuser',
                                               'groups', 'user_permissions')}),
                (_('Important dates'), {'fields': ('last_login', 'date_joined')}),
            )
            
        admin.site.register(LinkedInUser, LinkedInUserAdmin)
