### ISSUE TITLE
Migration file missing?

### ISSUE THREAD

**Issue by shulhi** [mishbahr/django-users2#21]
My django model is like this,
```
class Person(User):
    person_id = models.CharField('person id', max_length=254)
    person_id_type = models.CharField('person id type', max_length=254)
    first_name = models.CharField('first name', max_length=254)
    last_name = models.CharField('last name', max_length=254)
    phone = models.CharField('phone', max_length=254)
    photo = models.ImageField(upload_to='photos', max_length=254)

    class Meta:
        verbose_name = 'Person'
        verbose_name_plural = 'Persons'
```

Migrations work fine if I run this locally. These migration scripts (from `./manage.py makemigrations`) are committed in the repo. I have docker container that will copy this repo and run `./manage.py migrate` but this will fail with error:
```
django.db.migrations.exceptions.NodeNotFoundError: Migration accounts.0001_initial dependencies reference nonexistent parent node ('users', '0003_auto_20160105_0955')
```
Reason it fails because my model migration script depends on `0003_auto_20160105_0955.py` and this script is no where to be found because it was generated by `django-users2`. 

To fix this I have to connect into the container and delete all the migration script, and recreate by running `./manage.py makemigrations`, only then the migration will work.

Any idea on how to solve this?

**Comment by mishbahr** [comment]
I haven't made any model changes recently.. but thanks you for reporting this. I'll look into this as soon as I can.

In the meantime try changing the dependency for for 'Person' model migration to '__latest__' 

Regards

Mishbah

**Comment by shulhi** [comment]
@mishbahr that works, but that's more like a hacky solution. Where can I find the location of the said migration file? I tried searching but can't find it. If I can take a look at it, that will let me know what sort of fields that are changed.

**Comment by mishbahr** [comment]
Yep. I agree. From what I can tell, from your traceback there must be a missing migration. When you run `makemigrations` without an appname .. it looks though all your packages and creates migrations if needed. So it probably created a migration for `django-users`. But as the site packages are not versioned.. You won't have the same migration file in the server.

I'll investigate this as soon as I can.

**Comment by shulhi** [comment]
@mishbahr Thanks! But do you know where the auto-generated migration is stored?

**Comment by mishbahr** [comment]
Assuming you are using virtualenv.. it should be in your `site-packages/users/migrations/`

**Comment by shulhi** [comment]
This is the changes.

```
# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_last_login_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
    ]
```

**Comment by mishbahr** [comment]
The `User` model inherits `PermissionsMixin` and that's been charged recently in this commit: https://github.com/django/django/commit/72f6513ebaa7a3fd43c26300e9a8c430dc07cdb

I'll have to figure out a way to fix this while maintaining backward compatibility. Thank you for your help.

**Comment by mishbahr** [comment]
@shulhi which version of django are you using?

**Comment by shulhi** [comment]
@mishbahr I'm using django 1.9.1

**Comment by mishbahr** [comment]
Thanks @shulhi for reporting this! I've pushed the fix to PyPi :-)

**Comment by shulhi** [comment]
@mishbahr Great! Thanks for this awesome package :+1:
