### ISSUE TITLE
Support UUID as primary key

### ISSUE THREAD

**Issue by shulhi** [mishbahr/django-users2#22]
Is there a way I can make my custom user model primary key to use UUID? Right now, I can have another primary key column set as `UUIDField` but this leads to integer out of range error when adding user to group.

The table `users_user_groups` is expecting `user_id` as `int4` and this doesn't match with my user model which used `UUIDField` causing the integer out of range error.

**Comment by mishbahr** [comment]
You can define your own custom user model. Something like this should work. 

	from django.db import models
	
	from users.models import AbstractUser


	class CustomUser(AbstractUser):

		id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)


	    class Meta(AbstractUser.Meta):
	        swappable = 'AUTH_USER_MODEL'


Update your project settings to use your `CustomUser` model:

	AUTH_USER_MODEL = 'your_app.CustomUser'

Hope this helps. Thanks.

— Mishbah
