### ISSUE TITLE
Override `delete` in queryset

### ISSUE THREAD

**Issue by shulhi** [mishbahr/django-users2#23]
How do I override `delete` in queryset? I can override `delete` in each model but that will only work if I'm dealing with object directly like so, `Person.objects.get(pk=1).delete()`. 

But this won't work, `Person.objects.filter(pk=1).delete()` because it is returning a queryset object, and it is calling delete from the queryset. I tried to inherit your `UserManager` and override the `delete` method there, but it doesn't work.

**Comment by mishbahr** [comment]
There are few ways to delete an object via django ORM.

To delete it directly:

    Person.objects.filter(id=id).delete()

To delete it from an instance:
 
    person = Person.objects.get(id=id)
    person.delete()

Please refer to django documentation.

**Comment by shulhi** [comment]
@mishbahr I understood that. What I mean is that, I would like to override the default behavior of `delete`.

Anyway, I got it to work but not sure if it is the right way to do it.

```
class SoftDeleteInheritanceQuerySet(InheritanceQuerySet):
    def delete(self):
        super(SoftDeleteInheritanceQuerySet, self).update(is_deleted=True)


class SoftDeleteUserInheritanceManager(SoftDeleteUserManager):
    def get_queryset(self):
        return SoftDeleteInheritanceQuerySet(self.model).select_subclasses()

    get_query_set = get_queryset


class SoftDeleteAbstractUser(AbstractUser):
    objects = SoftDeleteUserInheritanceManager()
    base_objects = SoftDeleteUserManager()

    class Meta:
        abstract = True
```

**Comment by mishbahr** [comment]
Hey @shulhi, sorry I misunderstood you. I'm no expert in this, but delete objects method should be in the model itself, rather than its manager? You'll probably want to override the manger to exclude "deleted" objects.

See docs https://docs.djangoproject.com/en/1.9/ref/models/instances/#deleting-objects
