### ISSUE TITLE
the requirements of django-model-utils can't find at pypi any more

### ISSUE THREAD

**Issue by newerBkl** [mishbahr/django-users2#27]
Hi,
My Django' version is 1.11, I  could't setup django-users2 .The error is the requirements of  django-model-utils  was't .Also I could't find the django-model-utils at pypi ,Maybe it has changed name ?
django-modeladmin-utils ?
Could you check it? Many Thanks

**Comment by mishbahr** [comment]
https://pypi.python.org/pypi/django-model-utils

Looks like django-model-utils 3.0.0 
+ Drop support for Python 2.6.
+ Drop support for Django 1.4, 1.5, 1.6, 1.7.

What version of python/django are you using?

`django-users2` don't have a specific version requirement for `django-model-utils`

**Comment by newerBkl** [comment]
Many thanks.I' have found the django-model-utils and installation was sucessfully.
